# Generated by Django 2.2 on 2019-07-02 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametros', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombCarg', models.CharField(default='', max_length=750, verbose_name='Nombre Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Logros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechLogr', models.DateTimeField(auto_now=True, verbose_name='Fecha de Logro')),
                ('NombLogr', models.CharField(default='', max_length=100, verbose_name='Nombre de Logro')),
                ('DescLogr', models.CharField(default='', max_length=750, verbose_name='Descripcion Logro')),
                ('id_TipoLogr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.TipoLogr', verbose_name='Tipo de logro')),
                ('id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
            },
        ),
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombHabi', models.CharField(default='', max_length=155, verbose_name='Nombre Habilidad')),
                ('NiveHabi', models.CharField(default='', max_length=50, verbose_name='Nivel Habilidad')),
                ('id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario', verbose_name='Numero Usuario')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empresa', models.CharField(default='', max_length=225, verbose_name='Empresa')),
                ('FechInic', models.DateTimeField(auto_now=True, verbose_name='Fecha de Inicio')),
                ('FechFin', models.DateTimeField(auto_now=True, verbose_name='Fecha de Finalizacion')),
                ('Funciones', models.CharField(default='', max_length=500, verbose_name='Funciones')),
                ('Logros', models.CharField(default='', max_length=500, verbose_name='Logros')),
                ('id_Cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.Cargo', verbose_name='Cargo')),
                ('id_Ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Ciudad', verbose_name='Ciudad')),
                ('id_Departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Departamento', verbose_name='Departamento')),
                ('id_Pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Pais', verbose_name='Pais')),
                ('id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencias',
            },
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instituto', models.CharField(default='', max_length=155, verbose_name='Instituto')),
                ('Titulo', models.CharField(default='', max_length=155, verbose_name='Titulo')),
                ('FechaGrado', models.DateTimeField(verbose_name='Fecha de Grado')),
                ('id_Ciudades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Ciudad', verbose_name='Ciudad')),
                ('id_Departamentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Departamento', verbose_name='Departamento')),
                ('id_Paises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Pais', verbose_name='Pais')),
                ('id_TipoEstu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.TipoEduc', verbose_name='Tipo de Educación')),
                ('id_Usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'educacion',
                'verbose_name_plural': 'educaciones',
            },
        ),
        migrations.CreateModel(
            name='DatoUsua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PerfProf', models.CharField(default='', max_length=200, verbose_name='Perfil Profesional')),
                ('Genero', models.CharField(default='', max_length=45, verbose_name='Genero')),
                ('Telefono', models.CharField(default='', max_length=45, verbose_name='Telefono')),
                ('Direccion', models.CharField(default='', max_length=255, verbose_name='Direccion')),
                ('id_Departamentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Departamento', verbose_name='Departamento')),
                ('id_EstaCivi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.EstaCivi', verbose_name='Estado Civil')),
                ('id_Etnia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Etnia', verbose_name='Etnia')),
                ('id_Pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Pais', verbose_name='Pais')),
                ('id_TipoDocu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.TipoDocu', verbose_name='Tipo Documento')),
                ('id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario', verbose_name='Numero Usuario')),
            ],
            options={
                'verbose_name': 'Datos Usuario',
                'verbose_name_plural': 'Datos Usuarios',
            },
        ),
    ]
