# Generated by Django 2.2 on 2019-07-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombUsua', models.CharField(default='', max_length=255, verbose_name='Nombre Usuario')),
                ('ApelUsua', models.CharField(default='', max_length=255, verbose_name='Apellido Usuario')),
                ('EmaiUsua', models.CharField(default='', max_length=255, verbose_name='Correo Usuario')),
                ('PassUsua', models.CharField(default='', max_length=255, verbose_name='Contraseña usuario')),
                ('EstaUsua', models.CharField(default='', max_length=50, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
