# Generated by Django 2.2 on 2019-07-02 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstaCivi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombEstaCivi', models.CharField(default='', max_length=50, verbose_name='Estado Civil')),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estados Civiles',
            },
        ),
        migrations.CreateModel(
            name='Etnia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombEtni', models.CharField(default='', max_length=50, verbose_name='Nombre Etnia')),
            ],
            options={
                'verbose_name': 'Etnia',
                'verbose_name_plural': 'Etnias',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombPais', models.CharField(default='', max_length=155, verbose_name='Nombre Pais')),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='TipoDocu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombTipoDocu', models.CharField(default='', max_length=50, verbose_name='Tipo Documento')),
            ],
            options={
                'verbose_name': 'Tipo Documento',
                'verbose_name_plural': 'Tipos de Documentos',
            },
        ),
        migrations.CreateModel(
            name='TipoEduc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombTipoEduc', models.CharField(default='', max_length=50, verbose_name='Tipo Estudio')),
            ],
            options={
                'verbose_name': 'Tipo Estudio',
                'verbose_name_plural': 'Tipos de Estudios',
            },
        ),
        migrations.CreateModel(
            name='TipoLogr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombTipoLogr', models.CharField(default='', max_length=50, verbose_name=' Tipo Logro')),
            ],
            options={
                'verbose_name': 'Tipo Logro',
                'verbose_name_plural': 'Tipos de Logros',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombDepa', models.CharField(default='', max_length=155, verbose_name='Nombre de Departamento')),
                ('id_Paises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Pais', verbose_name='Pais')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombCiud', models.CharField(default='', max_length=155, verbose_name='Nombre Ciudad')),
                ('id_Departamentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Departamento', verbose_name='Departamento')),
                ('id_Paises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Pais', verbose_name='Pais')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
    ]
